# Generated by Django 5.0.7 on 2024-08-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
