# Generated by Django 4.2.10 on 2024-02-22 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dish_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MenuType',
            fields=[
                ('menu_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.menutype')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
            options={
                'unique_together': {('restaurant', 'menu_type')},
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menus',
            field=models.ManyToManyField(through='restaurants.RestaurantMenu', to='restaurants.menutype'),
        ),
        migrations.CreateModel(
            name='MenuDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.dish')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurantmenu')),
            ],
            options={
                'unique_together': {('menu', 'dish')},
            },
        ),
    ]
