# Generated by Django 5.0.7 on 2026-02-15 08:38

import restaurants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menudish',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menudish',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='menudish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=restaurants.models.dish_image_upload_path),
        ),
        migrations.AddField(
            model_name='menudish',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menudish',
            name='is_veg',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menudish',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='menudish',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantmenu',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantmenu',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurantmenu',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
